### PR TITLE
ImGui Bindings

### PR DESCRIPTION
**Pull request by weshoke**
* Add a large chunk of ImGui bindings
* Add ImGui enums
* Fix shutdown segfault if engine doesn't exist
* Use `polyscope_bindings.imgui` directly
* Add basic demo

### CODE REVIEW

**Comment by nmwsharp** [comment]
This all seems awesome! It all looks good after a quick glance. Tomorrow I'll pull down the code and try writing some simple UIs just to look for any snags, but I think this will be good to go. Thanks!

**Comment by weshoke** [comment]
One divergence from the C++ bindings is how to handle in/out parameters passed by pointer.  There aren't great solutions to make this 1:1 with the Python interface, so I chose the following pattern:

```
def Combo(
    label: str, current_item: int, items: List[str], popup_max_height_in_items: int - 1
) -> Tuple[bool, int]: ...
```

Also, in this case, the `size` argument is implicit in the length of the `List`, which isn't the case in the C++ signature.

**Comment by nmwsharp** [comment]
Merged in #10! I added a few small things and fixed a couple incidental typos in the bindings.

With this much code being added, there are probably a few bugs lurking somewhere :) But that's OK, we can let folks start using this and fix bugs as they come in.

Thanks again for making this significant contribution!

**Comment by nmwsharp** [comment]
For the in/out parameters, that makes perfect sense of course. I don't think there's really any other way to do it in Python.

**Comment by nmwsharp** [comment]
@weshoke thanks again for adding these bindings, many people are using them!

I'm resurrecting this very old thread to ask a question: Over time ImGui's API is gradually changing, so these bindings are drifting. I guess we need to have a process for updating them if we want to stay up to date with ImGui.

Do you have any tips for how to update these, beyond lots of manual diffing & change-watching? When you generated these, did you use any automatic tooling or do it manually?

**Comment by weshoke** [comment]
I did it all by hand.  It doesn't take long.  You just have to slog through it.  I think it could be automated, but I'd have to look at the bindings to check.

For other projects where I've generated the bindings, I've always found you need some kind of manual override of any autogenerated bindings.

I've played around using LLMs for this kind of thing.  It works surprisingly well but requires supervision.

**Comment by nmwsharp** [comment]
Got it, thanks for the quick response! I guess I'll plan to do a full-pass through some time soon and fix anything which has drifted.

Good to know that automatic tools probably aren't sufficient out-of-the-box. (And LLMs.... :exploding_head:)

**Comment by weshoke** [comment]
LLMs can be pretty good at generating the boilerplate if you provide a few examples across the spread of API data types

**Comment by weshoke** [comment]
@nmwsharp 

GPT4 generated this from a small section of the code I gave it.

```
"Name","Return Type","Argument","Argument Type","Description"
"SetNextWindowPos","void","pos, cond, pivot","const ImVec2&, ImGuiCond (default: 0), const ImVec2& (default: ImVec2(0, 0))","Set next window position. Call before Begin()."
"SetNextWindowSize","void","size, cond","const ImVec2&, ImGuiCond (default: 0)","Set next window size. Call before Begin()."
"SetNextWindowSizeConstraints","void","size_min, size_max, custom_callback, custom_callback_data","const ImVec2&, const ImVec2&, ImGuiSizeCallback (default: NULL), void* (default: NULL)","Set next window size limits. Use callback for non-trivial constraints."
"SetNextWindowContentSize","void","size","const ImVec2&","Set next window content size. Call before Begin()."
"SetNextWindowCollapsed","void","collapsed, cond","bool, ImGuiCond (default: 0)","Set next window collapsed state. Call before Begin()."
"SetNextWindowFocus","void","-","-","Set next window to be focused/top-most. Call before Begin()."
"SetNextWindowScroll","void","scroll","const ImVec2&","Set next window scrolling value."
"SetNextWindowBgAlpha","void","alpha","float","Set next window background color alpha."
"SetWindowPos","void","pos, cond","const ImVec2&, ImGuiCond (default: 0)","Set current window position. Call within Begin()/End()."
"SetWindowSize","void","size, cond","const ImVec2&, ImGuiCond (default: 0)","Set current window size. Call within Begin()/End()."
"SetWindowCollapsed","void","collapsed, cond","bool, ImGuiCond (default: 0)","Set current window collapsed state."
"SetWindowFocus","void","-","-","Set current window to be focused/top-most."
"SetWindowFontScale","void","scale","float","[OBSOLETE] Set font scale. Adjust for all windows."
"SetWindowPos","void","name, pos, cond","const char*, const ImVec2&, ImGuiCond (default: 0)","Set named window position."
"SetWindowSize","void","name, size, cond","const char*, const ImVec2&, ImGuiCond (default: 0)","Set named window size."
"SetWindowCollapsed","void","name, collapsed, cond","const char*, bool, ImGuiCond (default: 0)","Set named window collapsed state."
"SetWindowFocus","void","name","const char*","Set named window to be focused/top-most."

```

I then have it 2 example bindings and it generated this code for the first 5 rows in the table:

```cpp
m.def("SetNextWindowPos", 
    [](const Vec2T& pos, ImGuiCond cond, const Vec2T& pivot) {
        ImGui::SetNextWindowPos(to_vec2(pos), cond, to_vec2(pivot));
    },
    py::arg("pos"),
    py::arg("cond") = 0,
    py::arg("pivot") = std::make_tuple(0., 0.)
);

m.def("SetNextWindowSize", 
    [](const Vec2T& size, ImGuiCond cond) {
        ImGui::SetNextWindowSize(to_vec2(size), cond);
    },
    py::arg("size"),
    py::arg("cond") = 0
);

m.def("SetNextWindowSizeConstraints", 
    [](const Vec2T& size_min, const Vec2T& size_max, ImGuiSizeCallback custom_callback, void* custom_callback_data) {
        // This assumes you have a function to_vec2. If not, you'll need to handle the conversion from Vec2T to ImVec2.
        ImGui::SetNextWindowSizeConstraints(to_vec2(size_min), to_vec2(size_max), custom_callback, custom_callback_data);
    },
    py::arg("size_min"),
    py::arg("size_max"),
    py::arg("custom_callback") = NULL,
    py::arg("custom_callback_data") = NULL
);

m.def("SetNextWindowContentSize", 
    [](const Vec2T& size) {
        ImGui::SetNextWindowContentSize(to_vec2(size));
    },
    py::arg("size")
);

m.def("SetNextWindowCollapsed", 
    [](bool collapsed, ImGuiCond cond) {
        ImGui::SetNextWindowCollapsed(collapsed, cond);
    },
    py::arg("collapsed"),
    py::arg("cond") = 0
);
```

**Pull request closed without merging**
