### PR TITLE
PR related to the python binding of variable node radius of CurveNetworks

### PR DESCRIPTION
**Pull request by xarthurx**
PR related to the python binding of https://github.com/nmwsharp/polyscope/pull/180

### CODE REVIEW

**Comment by xarthurx** [comment]
Hi @nmwsharp , sorry to bother. As I'm keep receiving notification from this PR, just out of curiosity:

are you using it just as a PR for continuous development or all the additional code is related to this PR?

**Comment by nmwsharp** [comment]
@xarthurx yes actually :) I must have forgotten that this branch was originally from your commit when I started using it as development branch, my apologies for the notification spam!

I'm going to merge it in in the next few days, so the endless notifications will be over soon.

**Comment by nmwsharp** [comment]
@xarthurx I'll move this over to a new PR to clean up the history.

**Comment by xarthurx** [comment]
Ha. No bother at all, and actually interesting to see the progress time to time.
Thanks for the answer.

**Pull request closed without merging**
